
version: '2'

services:
  storesmanagement:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: mvn spring-boot:run -Dspring.profiles.active=dev,docker-mysql
    ports:
      - "9888:9888"
    depends_on:
      - db
    volumes:
      - .:/code
  db:
    image: registry.prod.auction.local:5000/percona-server
    ports:
      - "11306:3306"
    environment:
      MYSQL_DATABASE: 'sspms'
      MYSQL_ROOT_PASSWORD: 'tenxdev'
